In [ ]:
# import requests

# def prepRequest(code: str, cookie=COOKIE):
#   url = f"https://datanalysis-morningstar-com-au.ezproxy-f.deakin.edu.au/ftl/company/financialprint?xtm-licensee=datpremium&xsl-printfriendly=yes&ASXCode={code.upper()}&sy=2014-01-01&ey=2024-12-31&rt=A&filetype=html&download=html"

#   payload = {}
#   headers = {
#     'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
#     'Accept-Language': 'en-US,en;q=0.9,vi;q=0.8',
#     'Connection': 'keep-alive',
#     'Cookie': 'DEAKINID=fdb85afd.6032a8d46f580; s_ecid=MCMID%7C22219353595475332393079092042334992393; _mkto_trk=id:209-INQ-367&token:_mch-deakin.edu.au-1692615689060-71878; nmstat=8ce65ae9-31bc-f84e-e2c6-47cfc0a6738c; _dui=L2jFMKImOgptMyCT5m7uc/CtIBsXjR9QF9G58gQeQ+K6sEVX5Gt1FGlj+Rbc+lZ/BdQ2hToSIn5c4164Us1FIQ==; _ga_GGQJZHYDLG=GS1.1.1696640838.2.1.1696640838.60.0.0; _hjSessionUser_1265829=eyJpZCI6ImE5YTY1MzVjLWU0ZmEtNTBlNS04OWViLWM0MzFjZTliN2Y4MCIsImNyZWF0ZWQiOjE2OTY5MTcwNzMxNTEsImV4aXN0aW5nIjpmYWxzZX0=; _ga_87D1W17TVW=GS1.1.1696917073.1.0.1696917076.0.0.0; _ga_81EHZDQV0Y=GS1.1.1697418863.1.1.1697419002.51.0.0; _fbp=fb.2.1705707129901.1058185942; _gcl_au=1.1.1814875345.1709770694; _ga_PJ62ZHGZ0Q=GS1.1.1709786261.17.1.1709786285.0.0.0; _ga_PQG8RRGSQ6=GS1.1.1710242635.3.0.1710242635.0.0.0; aam_uuid=21890800830818085173030899688138560827; _ga_VJWZRWYE2C=GS1.1.1710731494.68.1.1710731572.0.0.0; _ga_R8E7LY4YEY=GS1.1.1710751391.4.0.1710751398.0.0.0; _ga_9LPQHKJQHS=GS1.1.1710751413.10.0.1710751421.0.0.0; _ga_EQHBMS4L5Q=GS1.1.1710988102.42.1.1710988308.0.0.0; wpopdone=/course/master-business-analytics; s_vnum=1711890000588%26vn%3D2; AMCV_7D73CB3B5845DEF30A495C3B%40AdobeOrg=179643557%7CMCIDTS%7C19804%7CMCMID%7C22219353595475332393079092042334992393%7CMCAAMLH-1711596872%7C8%7CMCAAMB-1711596872%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1710999272s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C5.5.0%7CMCCIDH%7C-227983573; wisepops_visits=%5B%222024-03-21T03%3A34%3A32.549Z%22%2C%222024-03-14T00%3A59%3A32.479Z%22%2C%222024-03-14T00%3A59%3A13.237Z%22%2C%222023-10-16T01%3A14%3A12.743Z%22%2C%222023-10-16T01%3A13%3A51.182Z%22%5D; _tt_enable_cookie=1; _ttp=gXzvWCzL_F_Fo5ct4qSvb1ORjga; _scid=c47ad300-0ab0-451e-8766-84aad008cef5; _scid_r=c47ad300-0ab0-451e-8766-84aad008cef5; wisepops=%7B%22popups%22%3A%7B%7D%2C%22sub%22%3A0%2C%22ucrn%22%3A69%2C%22cid%22%3A%2241872%22%2C%22v%22%3A4%2C%22bandit%22%3A%7B%22recos%22%3A%7B%7D%7D%2C%22csd%22%3A1%7D; mbox=PC#76865f55a69d4603b63f346b9791973c.36_0#1774236942|session#4c00f57ead1e47b996629be719ddc939#1710994002; wisepops_visitor=%7B%22CGmQeXD9Dm%22%3A%22332c4bda-ff57-4904-9e8a-8349fc622483%22%7D; adcloud={%22_les_v%22:%22y%2Cdeakin.edu.au%2C1710993942%22}; s_nr=1710992144424-Repeat; _ga_0KZP27FW69=GS1.1.1711000988.28.0.1711000988.0.0.0; _ga_T637BKGYH6=GS1.1.1711236600.159.1.1711236611.0.0.0; _ga_0RST2B95FP=GS1.1.1711317956.227.0.1711317956.0.0.0; _ga_4FY7B4R1FG=GS1.1.1711317956.222.0.1711317956.0.0.0; _dui2=L2jFMKImOgptMyCT5m7uc/CtIBsXjR9QF9G58gQeQ+K6sEVX5Gt1FGlj+Rbc+lZ/BdQ2hToSIn5c4164Us1FIQ==; _ga2=GA1.1.254729127.1692328917; _ga_YEQ6SL40NP=GS1.1.1711333242.266.0.1711333248.0.0.0; _ga_MRD35CQJV9=GS1.1.1711333242.134.0.1711333248.0.0.0; client=5f267a319284001a60af1e7281c2932232337cdc; _gid=GA1.3.1318390933.1711333257; _ga_99X1PVMSVL=GS1.1.1711336721.14.0.1711337252.0.0.0; ezproxy=http://ezproxy-f.deakin.edu.au,4WNJ6NOx6I4quxi; ezproxyl=http://ezproxy-f.deakin.edu.au,4WNJ6NOx6I4quxi; ezproxyn=http://ezproxy-f.deakin.edu.au,4WNJ6NOx6I4quxi; JSESSIONID=C662A744DCE0C829E99C6D27D1C5F28C; _ga=GA1.3.254729127.1692328917; _gat=1; _ga_TQWX6VX42D=GS1.3.1711353015.8.1.1711353182.0.0.0; AWSALB=CsGx/x2s/I7yo9jfr1X9YhiMxiIJ3PFPpqOo+TqtBoSEXv77a75JpC1WowcV91C8r1psKDsP/y9k8ZQcPpD8q2kvNPBHObDtSxoTRQbve9w8cj2ZtjsH3Okhen1k; AWSALBCORS=CsGx/x2s/I7yo9jfr1X9YhiMxiIJ3PFPpqOo+TqtBoSEXv77a75JpC1WowcV91C8r1psKDsP/y9k8ZQcPpD8q2kvNPBHObDtSxoTRQbve9w8cj2ZtjsH3Okhen1k; AWSALB=dXmjXNecqUnl3FtfeEM8U3RP8zg9z7tutFjFxeSKnOqsUU39uF7KQRqQQqOGRAiqfDh9N6SAwoDEWF0KaRzo04GHQW1r668blDMjEOl15KyLsaOJeBq7ocOMW/B2; AWSALBCORS=dXmjXNecqUnl3FtfeEM8U3RP8zg9z7tutFjFxeSKnOqsUU39uF7KQRqQQqOGRAiqfDh9N6SAwoDEWF0KaRzo04GHQW1r668blDMjEOl15KyLsaOJeBq7ocOMW/B2; client=5f267a319284001a60af1e7281c2932232337cdc',
#     'Referer': 'https://datanalysis-morningstar-com-au.ezproxy-f.deakin.edu.au/ftl/company/financialprint?xtm-licensee=datpremium&xsl-printfriendly=yes&ASXCode=WDS&sy=2014-01-01&ey=2024-12-31&rt=A',
#     'Sec-Fetch-Dest': 'document',
#     'Sec-Fetch-Mode': 'navigate',
#     'Sec-Fetch-Site': 'same-origin',
#     'Sec-Fetch-User': '?1',
#     'Upgrade-Insecure-Requests': '1',
#     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
#     'sec-ch-ua': '"Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"',
#     'sec-ch-ua-mobile': '?0',
#     'sec-ch-ua-platform': '"macOS"'
#   }

#   response = requests.request("GET", url, headers=headers, data=payload)
#   return response.text

'DefaultEndpointsProtocol=https;AccountName=asxdata;AccountKey=/FVSuTy4xEq3tvPMT+eBUs+9ux83Y/tANgAffh7ZKdaaaTk+lqstZW9SE5ZEWohMR4LIp4zpdsHv+AStPWycXQ==;EndpointSuffix=core.windows.net'

In [25]:
# import os
# from datetime import datetime

# def store_financial_data(asx_codes, html_list):
#     """
#     Stores an HTML string for each ASX code in a list to a file in a structured directory, 
#     using timestamps for file naming.

#     Parameters:
#     - asx_codes: List of ASX codes.
#     - html_list: List of HTML content strings, each corresponding to an ASX code.
#     """
#     if len(asx_codes) != len(html_list):
#         raise ValueError("The length of ASX codes and HTML list must be the same.")
    
#     base_dir = 'FinancialData'
#     current_year = datetime.now().strftime("%Y")

#     for asx_code, html in zip(asx_codes, html_list):
#         sub_dir = f'{base_dir}/{asx_code}/{current_year}/RawHTML'
#         print(f"Creating directory: {sub_dir}")
#         os.makedirs(sub_dir, exist_ok=True)  # Ensure the directory exists
#         file_name = f"{asx_code}.html"
#         full_path = os.path.join(sub_dir, file_name)
        
#         with open(full_path, 'w', encoding='utf-8') as file:
#             file.write(html)
            
#         print(f'File saved: {full_path}')

"<!DOCTYPE html>\n<html lang='en'>\n<head>\n<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n<title>Shibboleth Authentication Request</title></head><body onload='EZproxyCheckBack()'><form name='EZproxyForm' method='POST' action='https://signon.deakin.edu.au/idp/profile/SAML2/POST/SSO'><input type='hidden' name='RelayState' value='ezp.2aHR0cHM6Ly9kYXRhbmFseXNpcy5tb3JuaW5nc3Rhci5jb20uYXUvZnRsL2NvbXBhbnkvZmluYW5jaWFscHJpbnQ.eHRtLWxpY2Vuc2VlPWRhdHByZW1pdW0meHNsLXByaW50ZnJpZW5kbHk9eWVzJkFTWENvZGU9WllVUyZzeT0yMDE0LTAxLTAxJmV5PTIwMjQtMTItMzEmcnQ9QSZmaWxldHlwZT1odG1sJmRvd25sb2FkPWh0bWw-'>\n<input type='hidden' name='SAMLRequest' value='PD94bWwgdmVyc2lvbj0iMS4wIj8+CjxzYW1scDpBdXRoblJlcXVlc3QgeG1sbnM6c2FtbHA9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpwcm90b2NvbCIgRGVzdGluYXRpb249Imh0dHBzOi8vc2lnbm9uLmRlYWtpbi5lZHUuYXUvaWRwL3Byb2ZpbGUvU0FNTDIvUE9TVC9TU08iIElEPSJfMTcxMTk1ODYyOTM4NDAxIiBJc3N1ZUluc3RhbnQ9IjIwMjQtMDQtMDFUMDg6MDM6NDlaIiBWZXJzaW9uPSIyLjAiPjxzYW1sOklzc3VlciB4bWxuczpzYW1sPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj5odHRwczovL2V6cHJveHktZjEuaXRzLmRlYWtpbi5lZHUuYXUvc2hpYmJvbGV0aDwvc2FtbDpJc3N1ZXI+PHNhbWxwOk5hbWVJRFBvbGljeSBBbGxvd0NyZWF0ZT0iMSIvPjwvc2FtbHA6QXV0aG5SZXF1ZXN0Pgo='>\nIf your browser does not continue automatically, click <input type='submit' value='here'>\r\n</form><form name='EZproxyTrack'><input type='hidden' name='back' value='1'><script language='JavaScript'>\r\n<!--\r\nfunction EZproxyCheckBack() {  var goForward = (document.EZproxyTrack.back.value==1);  document.EZproxyTrack.back.value=2;  document.EZproxyTrack.back.defaultValue=2;  if (goForward) { document.EZproxyForm.submit(); }}\r\n-->\r\n</script></body></html>\r\n"

# RUN here :)))

In [27]:
import os
from dotenv import load_dotenv
from IPython.display import display, HTML
from io import StringIO

import pandas as pd
import numpy as np
import yfinance as yf

In [ ]:
load_dotenv()
COOKIE = os.environ.get('COOKIE')
AZR_CONNECTION_STRING = os.environ.get('AZR_CONNECTION_STRING')

In [28]:
from azure.storage.blob import BlobServiceClient, BlobClient
import os

def download_data_from_blob(connection_string, container_name, download_folder):
    """
    Downloads files from an Azure Blob Storage container to a local directory.

    Parameters:
    - connection_string: Your Azure Blob Storage account connection string.
    - container_name: The name of the Azure Blob Storage container from which files will be downloaded.
    - download_folder: The local directory to which the files will be downloaded.
    """
    # Create the BlobServiceClient object
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    # Get the container client
    container_client = blob_service_client.get_container_client(container_name)
    
    # Create local directory if it does not exist
    if not os.path.exists(download_folder):
        os.makedirs(download_folder)
    
    # List all blobs in the container
    blob_list = container_client.list_blobs()
    for blob in blob_list:
        blob_client = container_client.get_blob_client(blob)
        download_file_path = os.path.join(download_folder, blob.name)

        # Create directory structure if it does not exist
        os.makedirs(os.path.dirname(download_file_path), exist_ok=True)
        
        print(f"Downloading blob to {download_file_path}...")
        # Download the blob
        with open(download_file_path, "wb") as download_file:
            download_file.write(blob_client.download_blob().readall())
        print(f"Downloaded {blob.name} successfully.")

# Example usage
connection_string = AZR_CONNECTION_STRING
container_name = "asxcompdata"
download_folder = "FinancialData"

# Call the function to start downloading files
if not os.path.exists(download_folder):
    download_data_from_blob(connection_string, container_name, download_folder)

Downloading blob to FinancialData/14D/2024/RawHTML/14D.html...
Downloaded 14D/2024/RawHTML/14D.html successfully.
Downloading blob to FinancialData/1AD/2024/RawHTML/1AD.html...
Downloaded 1AD/2024/RawHTML/1AD.html successfully.
Downloading blob to FinancialData/1AG/2024/RawHTML/1AG.html...
Downloaded 1AG/2024/RawHTML/1AG.html successfully.
Downloading blob to FinancialData/1AL/2024/RawHTML/1AL.html...
Downloaded 1AL/2024/RawHTML/1AL.html successfully.
Downloading blob to FinancialData/1ST/2024/RawHTML/1ST.html...
Downloaded 1ST/2024/RawHTML/1ST.html successfully.
Downloading blob to FinancialData/2BE/2024/RawHTML/2BE.html...
Downloaded 2BE/2024/RawHTML/2BE.html successfully.
Downloading blob to FinancialData/360/2024/RawHTML/360.html...
Downloaded 360/2024/RawHTML/360.html successfully.
Downloading blob to FinancialData/3DA/2024/RawHTML/3DA.html...
Downloaded 3DA/2024/RawHTML/3DA.html successfully.
Downloading blob to FinancialData/3DP/2024/RawHTML/3DP.html...
Downloaded 3DP/2024/RawHTML/3DP.html successfully.
Downloading blob to FinancialData/3PL/2024/RawHTML/3PL.html...
Downloaded 3PL/2024/RawHTML/3PL.html successfully.
Downloading blob to FinancialData/4CE/2024/RawHTML/4CE.html...
Downloaded 4CE/2024/RawHTML/4CE.html successfully.
Downloading blob to FinancialData/4DS/2024/RawHTML/4DS.html...
Downloaded 4DS/2024/RawHTML/4DS.html successfully.
Downloading blob to FinancialData/5GN/2024/RawHTML/5GN.html...
Downloaded 5GN/2024/RawHTML/5GN.html successfully.
Downloading blob to FinancialData/88E/2024/RawHTML/88E.html...
Downloaded 88E/2024/RawHTML/88E.html successfully.
Downloading blob to FinancialData/8CO/2024/RawHTML/8CO.html...
Downloaded 8CO/2024/RawHTML/8CO.html successfully.
Downloading blob to FinancialData/8EC/2024/RawHTML/8EC.html...
Downloaded 8EC/2024/RawHTML/8EC.html successfully.
Downloading blob to FinancialData/8IH/2024/RawHTML/8IH.html...
Downloaded 8IH/2024/RawHTML/8IH.html successfully.
Downloading blob to FinancialData/8VI/2024/RawHTML/8VI.html...
Downloaded 8VI/2024/RawHTML/8VI.html successfully.
Downloading blob to FinancialData/9SP/2024/RawHTML/9SP.html...
Downloaded 9SP/2024/RawHTML/9SP.html successfully.
Downloading blob to FinancialData/A1G/2024/RawHTML/A1G.html...
Downloaded A1G/2024/RawHTML/A1G.html successfully.
Downloading blob to FinancialData/A1M/2024/RawHTML/A1M.html...
Downloaded A1M/2024/RawHTML/A1M.html successfully.
Downloading blob to FinancialData/A200/2024/RawHTML/A200.html...
Downloaded A200/2024/RawHTML/A200.html successfully.
Downloading blob to FinancialData/A2B/2024/RawHTML/A2B.html...
Downloaded A2B/2024/RawHTML/A2B.html successfully.
Downloading blob to FinancialData/A2M/2024/RawHTML/A2M.html...
Downloaded A2M/2024/RawHTML/A2M.html successfully.
Downloading blob to FinancialData/A3D/2024/RawHTML/A3D.html...
Downloaded A3D/2024/RawHTML/A3D.html successfully.
Downloading blob to FinancialData/A40/2024/RawHTML/A40.html...
Downloaded A40/2024/RawHTML/A40.html successfully.
Downloading blob to FinancialData/A4N/2024/RawHTML/A4N.html...
Downloaded A4N/2024/RawHTML/A4N.html successfully.
Downloading blob to FinancialData/AAA/2024/RawHTML/AAA.html...
Downloaded AAA/2024/RawHTML/AAA.html successfully.
Downloading blob to FinancialData/AAC/2024/RawHTML/AAC.html...
Downloaded AAC/2024/RawHTML/AAC.html successfully.
Downloading blob to FinancialData/AAJ/2024/RawHTML/AAJ.html...
Downloaded AAJ/2024/RawHTML/AAJ.html successfully.
Downloading blob to FinancialData/AAP/2024/RawHTML/AAP.html...
Downloaded AAP/2024/RawHTML/AAP.html successfully.
Downloading blob to FinancialData/AAR/2024/RawHTML/AAR.html...
Downloaded AAR/2024/RawHTML/AAR.html successfully.
Downloading blob to FinancialData/ABA/2024/RawHTML/ABA.html...
Downloaded ABA/2024/RawHTML/ABA.html successfully.
Downloading blob to FinancialData/ABC/2024/RawHTML/ABC.html...
Downloaded ABC/2024/RawHTML/ABC.html successfully.
Downloading blob to FinancialData/ABL/2024/RawHTML/ABL.html...
Downloaded ABL/2024/RawHTML/ABL.html successfully.
Downloading blob to FinancialData/ABP/2024/RawHTML/ABP.html...
Downloaded ABP/2024/RawHTML/ABP.html successfully.
Downloading blob to FinancialData/ABR/2024/RawHTML/ABR.html...
Downloaded ABR/2024/RawHTML/ABR.html successfully.
Downloading blob to FinancialData/ABT/2024/RawHTML/ABT.html...
Downloaded ABT/2024/RawHTML/ABT.html successfully.
Downloading blob to FinancialData/ABV/2024/RawHTML/ABV.html...
Downloaded ABV/2024/RawHTML/ABV.html successfully.
Downloading blob to FinancialData/ABW/2024/RawHTML/ABW.html...
Downloaded ABW/2024/RawHTML/ABW.html successfully.
Downloading blob to FinancialData/ABX/2024/RawHTML/ABX.html...
Downloaded ABX/2024/RawHTML/ABX.html successfully.
Downloading blob to FinancialData/AC8/2024/RawHTML/AC8.html...
Downloaded AC8/2024/RawHTML/AC8.html successfully.
Downloading blob to FinancialData/ACB/2024/RawHTML/ACB.html...
Downloaded ACB/2024/RawHTML/ACB.html successfully.
Downloading blob to FinancialData/ACDC/2024/RawHTML/ACDC.html...
Downloaded ACDC/2024/RawHTML/ACDC.html successfully.
Downloading blob to FinancialData/ACF/2024/RawHTML/ACF.html...
Downloaded ACF/2024/RawHTML/ACF.html successfully.
Downloading blob to FinancialData/ACP/2024/RawHTML/ACP.html...
Downloaded ACP/2024/RawHTML/ACP.html successfully.
Downloading blob to FinancialData/ACQ/2024/RawHTML/ACQ.html...
Downloaded ACQ/2024/RawHTML/ACQ.html successfully.
Downloading blob to FinancialData/ACR/2024/RawHTML/ACR.html...
Downloaded ACR/2024/RawHTML/ACR.html successfully.
Downloading blob to FinancialData/ACS/2024/RawHTML/ACS.html...
Downloaded ACS/2024/RawHTML/ACS.html successfully.
Downloading blob to FinancialData/ACU/2024/RawHTML/ACU.html...
Downloaded ACU/2024/RawHTML/ACU.html successfully.
Downloading blob to FinancialData/ACW/2024/RawHTML/ACW.html...
Downloaded ACW/2024/RawHTML/ACW.html successfully.
Downloading blob to FinancialData/AD1/2024/RawHTML/AD1.html...
Downloaded AD1/2024/RawHTML/AD1.html successfully.
Downloading blob to FinancialData/AD8/2024/RawHTML/AD8.html...
Downloaded AD8/2024/RawHTML/AD8.html successfully.
Downloading blob to FinancialData/ADA/2024/RawHTML/ADA.html...
Downloaded ADA/2024/RawHTML/ADA.html successfully.
Downloading blob to FinancialData/ADD/2024/RawHTML/ADD.html...
Downloaded ADD/2024/RawHTML/ADD.html successfully.
Downloading blob to FinancialData/ADH/2024/RawHTML/ADH.html...
Downloaded ADH/2024/RawHTML/ADH.html successfully.
Downloading blob to FinancialData/ADI/2024/RawHTML/ADI.html...
Downloaded ADI/2024/RawHTML/ADI.html successfully.
Downloading blob to FinancialData/ADJ/2024/RawHTML/ADJ.html...
Downloaded ADJ/2024/RawHTML/ADJ.html successfully.
Downloading blob to FinancialData/ADN/2024/RawHTML/ADN.html...
Downloaded ADN/2024/RawHTML/ADN.html successfully.
Downloading blob to FinancialData/ADO/2024/RawHTML/ADO.html...
Downloaded ADO/2024/RawHTML/ADO.html successfully.
Downloading blob to FinancialData/ADR/2024/RawHTML/ADR.html...
Downloaded ADR/2024/RawHTML/ADR.html successfully.
Downloading blob to FinancialData/ADT/2024/RawHTML/ADT.html...
Downloaded ADT/2024/RawHTML/ADT.html successfully.
Downloading blob to FinancialData/ADV/2024/RawHTML/ADV.html...
Downloaded ADV/2024/RawHTML/ADV.html successfully.
Downloading blob to FinancialData/ADX/2024/RawHTML/ADX.html...
Downloaded ADX/2024/RawHTML/ADX.html successfully.
Downloading blob to FinancialData/ADY/2024/RawHTML/ADY.html...
Downloaded ADY/2024/RawHTML/ADY.html successfully.
Downloading blob to FinancialData/AEB/2024/RawHTML/AEB.html...
Downloaded AEB/2024/RawHTML/AEB.html successfully.
Downloading blob to FinancialData/AEE/2024/RawHTML/AEE.html...
Downloaded AEE/2024/RawHTML/AEE.html successfully.
Downloading blob to FinancialData/AEF/2024/RawHTML/AEF.html...
Downloaded AEF/2024/RawHTML/AEF.html successfully.
Downloading blob to FinancialData/AEG/2024/RawHTML/AEG.html...
Downloaded AEG/2024/RawHTML/AEG.html successfully.
Downloading blob to FinancialData/AEI/2024/RawHTML/AEI.html...
Downloaded AEI/2024/RawHTML/AEI.html successfully.
Downloading blob to FinancialData/AER/2024/RawHTML/AER.html...
Downloaded AER/2024/RawHTML/AER.html successfully.
Downloading blob to FinancialData/AEV/2024/RawHTML/AEV.html...
Downloaded AEV/2024/RawHTML/AEV.html successfully.
Downloading blob to FinancialData/AFA/2024/RawHTML/AFA.html...
Downloaded AFA/2024/RawHTML/AFA.html successfully.
Downloading blob to FinancialData/AFG/2024/RawHTML/AFG.html...
Downloaded AFG/2024/RawHTML/AFG.html successfully.
Downloading blob to FinancialData/AFI/2024/RawHTML/AFI.html...
Downloaded AFI/2024/RawHTML/AFI.html successfully.
Downloading blob to FinancialData/AFL/2024/RawHTML/AFL.html...
Downloaded AFL/2024/RawHTML/AFL.html successfully.
Downloading blob to FinancialData/AFP/2024/RawHTML/AFP.html...
Downloaded AFP/2024/RawHTML/AFP.html successfully.
Downloading blob to FinancialData/AFR/2024/RawHTML/AFR.html...
Downloaded AFR/2024/RawHTML/AFR.html successfully.
Downloading blob to FinancialData/AFT/2024/RawHTML/AFT.html...
Downloaded AFT/2024/RawHTML/AFT.html successfully.
Downloading blob to FinancialData/AGD/2024/RawHTML/AGD.html...
Downloaded AGD/2024/RawHTML/AGD.html successfully.
Downloading blob to FinancialData/AGE/2024/RawHTML/AGE.html...
Downloaded AGE/2024/RawHTML/AGE.html successfully.
Downloading blob to FinancialData/AGG/2024/RawHTML/AGG.html...
Downloaded AGG/2024/RawHTML/AGG.html successfully.
Downloading blob to FinancialData/AGH/2024/RawHTML/AGH.html...
Downloaded AGH/2024/RawHTML/AGH.html successfully.
Downloading blob to FinancialData/AGI/2024/RawHTML/AGI.html...
Downloaded AGI/2024/RawHTML/AGI.html successfully.
Downloading blob to FinancialData/AGJ/2024/RawHTML/AGJ.html...
Downloaded AGJ/2024/RawHTML/AGJ.html successfully.
Downloading blob to FinancialData/AGL/2024/RawHTML/AGL.html...
Downloaded AGL/2024/RawHTML/AGL.html successfully.
Downloading blob to FinancialData/AGM/2024/RawHTML/AGM.html...
Downloaded AGM/2024/RawHTML/AGM.html successfully.
Downloading blob to FinancialData/AGR/2024/RawHTML/AGR.html...
Downloaded AGR/2024/RawHTML/AGR.html successfully.
Downloading blob to FinancialData/AGS/2024/RawHTML/AGS.html...
Downloaded AGS/2024/RawHTML/AGS.html successfully.
Downloading blob to FinancialData/AGVT/2024/RawHTML/AGVT.html...
Downloaded AGVT/2024/RawHTML/AGVT.html successfully.
Downloading blob to FinancialData/AGX1/2024/RawHTML/AGX1.html...
Downloaded AGX1/2024/RawHTML/AGX1.html successfully.
Downloading blob to FinancialData/AGY/2024/RawHTML/AGY.html...
Downloaded AGY/2024/RawHTML/AGY.html successfully.
Downloading blob to FinancialData/AHF/2024/RawHTML/AHF.html...
Downloaded AHF/2024/RawHTML/AHF.html successfully.
Downloading blob to FinancialData/AHK/2024/RawHTML/AHK.html...
Downloaded AHK/2024/RawHTML/AHK.html successfully.
Downloading blob to FinancialData/AHL/2024/RawHTML/AHL.html...
Downloaded AHL/2024/RawHTML/AHL.html successfully.
Downloading blob to FinancialData/AHN/2024/RawHTML/AHN.html...
Downloaded AHN/2024/RawHTML/AHN.html successfully.
Downloading blob to FinancialData/AHQ/2024/RawHTML/AHQ.html...
Downloaded AHQ/2024/RawHTML/AHQ.html successfully.
Downloading blob to FinancialData/AHX/2024/RawHTML/AHX.html...
Downloaded AHX/2024/RawHTML/AHX.html successfully.
Downloading blob to FinancialData/AHY/2024/RawHTML/AHY.html...
Downloaded AHY/2024/RawHTML/AHY.html successfully.
Downloading blob to FinancialData/AHZ/2024/RawHTML/AHZ.html...
Downloaded AHZ/2024/RawHTML/AHZ.html successfully.
Downloading blob to FinancialData/AIA/2024/RawHTML/AIA.html...
Downloaded AIA/2024/RawHTML/AIA.html successfully.
Downloading blob to FinancialData/AIB/2024/RawHTML/AIB.html...
Downloaded AIB/2024/RawHTML/AIB.html successfully.
Downloading blob to FinancialData/AIQ/2024/RawHTML/AIQ.html...
Downloaded AIQ/2024/RawHTML/AIQ.html successfully.
Downloading blob to FinancialData/AIR/2024/RawHTML/AIR.html...
Downloaded AIR/2024/RawHTML/AIR.html successfully.
Downloading blob to FinancialData/AIS/2024/RawHTML/AIS.html...
Downloaded AIS/2024/RawHTML/AIS.html successfully.
Downloading blob to FinancialData/AIV/2024/RawHTML/AIV.html...
Downloaded AIV/2024/RawHTML/AIV.html successfully.
Downloading blob to FinancialData/AIY/2024/RawHTML/AIY.html...
Downloaded AIY/2024/RawHTML/AIY.html successfully.
Downloading blob to FinancialData/AIZ/2024/RawHTML/AIZ.html...
Downloaded AIZ/2024/RawHTML/AIZ.html successfully.
Downloading blob to FinancialData/AJC/2024/RawHTML/AJC.html...
Downloaded AJC/2024/RawHTML/AJC.html successfully.
Downloading blob to FinancialData/AJJ/2024/RawHTML/AJJ.html...
Downloaded AJJ/2024/RawHTML/AJJ.html successfully.
Downloading blob to FinancialData/AJL/2024/RawHTML/AJL.html...
Downloaded AJL/2024/RawHTML/AJL.html successfully.
Downloading blob to FinancialData/AJM/2024/RawHTML/AJM.html...
Downloaded AJM/2024/RawHTML/AJM.html successfully.
Downloading blob to FinancialData/AJQ/2024/RawHTML/AJQ.html...
Downloaded AJQ/2024/RawHTML/AJQ.html successfully.
Downloading blob to FinancialData/AJX/2024/RawHTML/AJX.html...
Downloaded AJX/2024/RawHTML/AJX.html successfully.
Downloading blob to FinancialData/AJY/2024/RawHTML/AJY.html...
Downloaded AJY/2024/RawHTML/AJY.html successfully.
Downloading blob to FinancialData/AKG/2024/RawHTML/AKG.html...
Downloaded AKG/2024/RawHTML/AKG.html successfully.
Downloading blob to FinancialData/AKM/2024/RawHTML/AKM.html...
Downloaded AKM/2024/RawHTML/AKM.html successfully.
Downloading blob to FinancialData/AKN/2024/RawHTML/AKN.html...
Downloaded AKN/2024/RawHTML/AKN.html successfully.
Downloading blob to FinancialData/AKP/2024/RawHTML/AKP.html...
Downloaded AKP/2024/RawHTML/AKP.html successfully.
Downloading blob to FinancialData/AL3/2024/RawHTML/AL3.html...
Downloaded AL3/2024/RawHTML/AL3.html successfully.
Downloading blob to FinancialData/AL8/2024/RawHTML/AL8.html...
Downloaded AL8/2024/RawHTML/AL8.html successfully.
Downloading blob to FinancialData/ALC/2024/RawHTML/ALC.html...
Downloaded ALC/2024/RawHTML/ALC.html successfully.
Downloading blob to FinancialData/ALF/2024/RawHTML/ALF.html...
Downloaded ALF/2024/RawHTML/ALF.html successfully.
Downloading blob to FinancialData/ALG/2024/RawHTML/ALG.html...
Downloaded ALG/2024/RawHTML/ALG.html successfully.
Downloading blob to FinancialData/ALI/2024/RawHTML/ALI.html...
Downloaded ALI/2024/RawHTML/ALI.html successfully.
Downloading blob to FinancialData/ALK/2024/RawHTML/ALK.html...
Downloaded ALK/2024/RawHTML/ALK.html successfully.
Downloading blob to FinancialData/ALL/2024/RawHTML/ALL.html...
Downloaded ALL/2024/RawHTML/ALL.html successfully.
Downloading blob to FinancialData/ALQ/2024/RawHTML/ALQ.html...
Downloaded ALQ/2024/RawHTML/ALQ.html successfully.
Downloading blob to FinancialData/ALT/2024/RawHTML/ALT.html...
Downloaded ALT/2024/RawHTML/ALT.html successfully.
Downloading blob to FinancialData/ALU/2024/RawHTML/ALU.html...
Downloaded ALU/2024/RawHTML/ALU.html successfully.
Downloading blob to FinancialData/ALX/2024/RawHTML/ALX.html...
Downloaded ALX/2024/RawHTML/ALX.html successfully.
Downloading blob to FinancialData/ALY/2024/RawHTML/ALY.html...
Downloaded ALY/2024/RawHTML/ALY.html successfully.
Downloading blob to FinancialData/AMA/2024/RawHTML/AMA.html...
Downloaded AMA/2024/RawHTML/AMA.html successfully.
Downloading blob to FinancialData/AMB/2024/RawHTML/AMB.html...
Downloaded AMB/2024/RawHTML/AMB.html successfully.
Downloading blob to FinancialData/AMC/2024/RawHTML/AMC.html...
Downloaded AMC/2024/RawHTML/AMC.html successfully.
Downloading blob to FinancialData/AMD/2024/RawHTML/AMD.html...
Downloaded AMD/2024/RawHTML/AMD.html successfully.
Downloading blob to FinancialData/AME/2024/RawHTML/AME.html...
Downloaded AME/2024/RawHTML/AME.html successfully.
Downloading blob to FinancialData/AMG/2024/RawHTML/AMG.html...
Downloaded AMG/2024/RawHTML/AMG.html successfully.
Downloading blob to FinancialData/AMH/2024/RawHTML/AMH.html...
Downloaded AMH/2024/RawHTML/AMH.html successfully.
Downloading blob to FinancialData/AMI/2024/RawHTML/AMI.html...
Downloaded AMI/2024/RawHTML/AMI.html successfully.
Downloading blob to FinancialData/AML/2024/RawHTML/AML.html...
Downloaded AML/2024/RawHTML/AML.html successfully.
Downloading blob to FinancialData/AMN/2024/RawHTML/AMN.html...
Downloaded AMN/2024/RawHTML/AMN.html successfully.
Downloading blob to FinancialData/AMO/2024/RawHTML/AMO.html...
Downloaded AMO/2024/RawHTML/AMO.html successfully.
Downloading blob to FinancialData/AMP/2024/RawHTML/AMP.html...
Downloaded AMP/2024/RawHTML/AMP.html successfully.
Downloading blob to FinancialData/AMS/2024/RawHTML/AMS.html...
Downloaded AMS/2024/RawHTML/AMS.html successfully.
Downloading blob to FinancialData/AMT/2024/RawHTML/AMT.html...
Downloaded AMT/2024/RawHTML/AMT.html successfully.
Downloading blob to FinancialData/AMX/2024/RawHTML/AMX.html...
Downloaded AMX/2024/RawHTML/AMX.html successfully.
Downloading blob to FinancialData/ANA/2024/RawHTML/ANA.html...
Downloaded ANA/2024/RawHTML/ANA.html successfully.
Downloading blob to FinancialData/ANG/2024/RawHTML/ANG.html...
Downloaded ANG/2024/RawHTML/ANG.html successfully.
Downloading blob to FinancialData/ANL/2024/RawHTML/ANL.html...
Downloaded ANL/2024/RawHTML/ANL.html successfully.
Downloading blob to FinancialData/ANN/2024/RawHTML/ANN.html...
Downloaded ANN/2024/RawHTML/ANN.html successfully.
Downloading blob to FinancialData/ANO/2024/RawHTML/ANO.html...
Downloaded ANO/2024/RawHTML/ANO.html successfully.
Downloading blob to FinancialData/ANP/2024/RawHTML/ANP.html...
Downloaded ANP/2024/RawHTML/ANP.html successfully.
Downloading blob to FinancialData/ANR/2024/RawHTML/ANR.html...
Downloaded ANR/2024/RawHTML/ANR.html successfully.
Downloading blob to FinancialData/ANS/2024/RawHTML/ANS.html...
Downloaded ANS/2024/RawHTML/ANS.html successfully.
Downloading blob to FinancialData/ANW/2024/RawHTML/ANW.html...
Downloaded ANW/2024/RawHTML/ANW.html successfully.
Downloading blob to FinancialData/ANZ/2024/RawHTML/ANZ.html...
Downloaded ANZ/2024/RawHTML/ANZ.html successfully.
Downloading blob to FinancialData/AO1/2024/RawHTML/AO1.html...
Downloaded AO1/2024/RawHTML/AO1.html successfully.
Downloading blob to FinancialData/AOA/2024/RawHTML/AOA.html...
Downloaded AOA/2024/RawHTML/AOA.html successfully.
Downloading blob to FinancialData/AOF/2024/RawHTML/AOF.html...
Downloaded AOF/2024/RawHTML/AOF.html successfully.
Downloading blob to FinancialData/AON/2024/RawHTML/AON.html...
Downloaded AON/2024/RawHTML/AON.html successfully.
Downloading blob to FinancialData/AOP/2024/RawHTML/AOP.html...
Downloaded AOP/2024/RawHTML/AOP.html successfully.
Downloading blob to FinancialData/AOU/2024/RawHTML/AOU.html...
Downloaded AOU/2024/RawHTML/AOU.html successfully.
Downloading blob to FinancialData/AOW/2024/RawHTML/AOW.html...
Downloaded AOW/2024/RawHTML/AOW.html successfully.
Downloading blob to FinancialData/APA/2024/RawHTML/APA.html...
Downloaded APA/2024/RawHTML/APA.html successfully.
Downloading blob to FinancialData/APC/2024/RawHTML/APC.html...
Downloaded APC/2024/RawHTML/APC.html successfully.
Downloading blob to FinancialData/APD/2024/RawHTML/APD.html...
Downloaded APD/2024/RawHTML/APD.html successfully.
Downloading blob to FinancialData/APE/2024/RawHTML/APE.html...
Downloaded APE/2024/RawHTML/APE.html successfully.
Downloading blob to FinancialData/APG/2024/RawHTML/APG.html...
Downloaded APG/2024/RawHTML/APG.html successfully.
Downloading blob to FinancialData/APH/2024/RawHTML/APH.html...
Downloaded APH/2024/RawHTML/APH.html successfully.
Downloading blob to FinancialData/API/2024/RawHTML/API.html...
Downloaded API/2024/RawHTML/API.html successfully.
Downloading blob to FinancialData/APL/2024/RawHTML/APL.html...
Downloaded APL/2024/RawHTML/APL.html successfully.
Downloading blob to FinancialData/APT/2024/RawHTML/APT.html...
Downloaded APT/2024/RawHTML/APT.html successfully.
Downloading blob to FinancialData/APV/2024/RawHTML/APV.html...
Downloaded APV/2024/RawHTML/APV.html successfully.
Downloading blob to FinancialData/APW/2024/RawHTML/APW.html...
Downloaded APW/2024/RawHTML/APW.html successfully.

In [ ]:
def load_financial_data():
    """
    Loads HTML content for each ASX code from files stored in a structured directory.
    
    Returns:
    - A dictionary where each key is an ASX code and the value is the HTML content of the file.
    """
    base_dir = 'FinancialData'
    financial_data = {}
    SYMBOLS = pd.read_csv('symbols.csv')['code']
    for asx_code_dir in os.listdir(base_dir):
        if asx_code_dir in SYMBOLS:
            print(asx_code_dir)
        if (asx_code_dir == '.DS_Store') or (asx_code_dir.lower() not in SYMBOLS.str.lower().values):
            continue
        asx_code_path = os.path.join(base_dir, asx_code_dir)
        for year_dir in os.listdir(asx_code_path):
            year_path = os.path.join(asx_code_path, year_dir)
            raw_html_dir = os.path.join(year_path, 'RawHTML')
            if os.path.isdir(raw_html_dir):
                for file_name in os.listdir(raw_html_dir):
                    if file_name.endswith('.html'):
                        file_path = os.path.join(raw_html_dir, file_name)
                        print(file_path)
                        with open(file_path, 'r', encoding='utf-8') as file:
                            html_content = file.read()
                            asx_code = file_name.split('.')[0]
                            financial_data[asx_code] = html_content
                            print(f'File loaded: {file_path}')
    
    return financial_data

In [ ]:
comp_data = load_financial_data()

FinancialData/GDX/2024/RawHTML/GDX.html
File loaded: FinancialData/GDX/2024/RawHTML/GDX.html
FinancialData/RARI/2024/RawHTML/RARI.html
File loaded: FinancialData/RARI/2024/RawHTML/RARI.html
FinancialData/AGG/2024/RawHTML/AGG.html
File loaded: FinancialData/AGG/2024/RawHTML/AGG.html
FinancialData/DJRE/2024/RawHTML/DJRE.html
File loaded: FinancialData/DJRE/2024/RawHTML/DJRE.html
FinancialData/QUE/2024/RawHTML/QUE.html
File loaded: FinancialData/QUE/2024/RawHTML/QUE.html
FinancialData/IKO/2024/RawHTML/IKO.html
File loaded: FinancialData/IKO/2024/RawHTML/IKO.html
FinancialData/ANZ/2024/RawHTML/ANZ.html
File loaded: FinancialData/ANZ/2024/RawHTML/ANZ.html
FinancialData/CKA/2024/RawHTML/CKA.html
File loaded: FinancialData/CKA/2024/RawHTML/CKA.html
FinancialData/RF1/2024/RawHTML/RF1.html
File loaded: FinancialData/RF1/2024/RawHTML/RF1.html
FinancialData/GME/2024/RawHTML/GME.html
File loaded: FinancialData/GME/2024/RawHTML/GME.html
FinancialData/TOP/2024/RawHTML/TOP.html
File loaded: FinancialData/TOP/2024/RawHTML/TOP.html
FinancialData/VDBA/2024/RawHTML/VDBA.html
File loaded: FinancialData/VDBA/2024/RawHTML/VDBA.html
FinancialData/ADH/2024/RawHTML/ADH.html
File loaded: FinancialData/ADH/2024/RawHTML/ADH.html
FinancialData/SUH/2024/RawHTML/SUH.html
File loaded: FinancialData/SUH/2024/RawHTML/SUH.html
FinancialData/MND/2024/RawHTML/MND.html
File loaded: FinancialData/MND/2024/RawHTML/MND.html
FinancialData/EMH/2024/RawHTML/EMH.html
File loaded: FinancialData/EMH/2024/RawHTML/EMH.html
FinancialData/BWP/2024/RawHTML/BWP.html
File loaded: FinancialData/BWP/2024/RawHTML/BWP.html
FinancialData/PFP/2024/RawHTML/PFP.html
File loaded: FinancialData/PFP/2024/RawHTML/PFP.html
FinancialData/CHN/2024/RawHTML/CHN.html
File loaded: FinancialData/CHN/2024/RawHTML/CHN.html
FinancialData/CNW/2024/RawHTML/CNW.html
File loaded: FinancialData/CNW/2024/RawHTML/CNW.html
FinancialData/SZL/2024/RawHTML/SZL.html
File loaded: FinancialData/SZL/2024/RawHTML/SZL.html
FinancialData/MML/2024/RawHTML/MML.html
File loaded: FinancialData/MML/2024/RawHTML/MML.html
FinancialData/PEX/2024/RawHTML/PEX.html
File loaded: FinancialData/PEX/2024/RawHTML/PEX.html
FinancialData/CKF/2024/RawHTML/CKF.html
File loaded: FinancialData/CKF/2024/RawHTML/CKF.html
FinancialData/SYD/2024/RawHTML/SYD.html
File loaded: FinancialData/SYD/2024/RawHTML/SYD.html
FinancialData/KGN/2024/RawHTML/KGN.html
File loaded: FinancialData/KGN/2024/RawHTML/KGN.html
FinancialData/TLX/2024/RawHTML/TLX.html
File loaded: FinancialData/TLX/2024/RawHTML/TLX.html
FinancialData/NXM/2024/RawHTML/NXM.html
File loaded: FinancialData/NXM/2024/RawHTML/NXM.html
FinancialData/QUB/2024/RawHTML/QUB.html
File loaded: FinancialData/QUB/2024/RawHTML/QUB.html
FinancialData/SPY/2024/RawHTML/SPY.html
File loaded: FinancialData/SPY/2024/RawHTML/SPY.html
FinancialData/VIC/2024/RawHTML/VIC.html
File loaded: FinancialData/VIC/2024/RawHTML/VIC.html
FinancialData/ROG/2024/RawHTML/ROG.html
File loaded: FinancialData/ROG/2024/RawHTML/ROG.html
FinancialData/GNM/2024/RawHTML/GNM.html
File loaded: FinancialData/GNM/2024/RawHTML/GNM.html
FinancialData/RCL/2024/RawHTML/RCL.html
File loaded: FinancialData/RCL/2024/RawHTML/RCL.html
FinancialData/MAG/2024/RawHTML/MAG.html
File loaded: FinancialData/MAG/2024/RawHTML/MAG.html
FinancialData/ABV/2024/RawHTML/ABV.html
File loaded: FinancialData/ABV/2024/RawHTML/ABV.html
FinancialData/ADO/2024/RawHTML/ADO.html
File loaded: FinancialData/ADO/2024/RawHTML/ADO.html
FinancialData/CA8/2024/RawHTML/CA8.html
File loaded: FinancialData/CA8/2024/RawHTML/CA8.html
FinancialData/CAT/2024/RawHTML/CAT.html
File loaded: FinancialData/CAT/2024/RawHTML/CAT.html
FinancialData/CGM/2024/RawHTML/CGM.html
File loaded: FinancialData/CGM/2024/RawHTML/CGM.html
FinancialData/TIN/2024/RawHTML/TIN.html
File loaded: FinancialData/TIN/2024/RawHTML/TIN.html
FinancialData/NTO/2024/RawHTML/NTO.html
File loaded: FinancialData/NTO/2024/RawHTML/NTO.html
FinancialData/KKL/2024/RawHTML/KKL.html
File loaded: FinancialData/KKL/2024/RawHTML/KKL.html
FinancialData/VCX/2024/RawHTML/VCX.html
File loaded: FinancialData/VCX/2024/RawHTML/VCX.html
FinancialData/VEA/2024/RawHTML/VEA.html
File loaded: FinancialData/VEA/2024/RawHTML/VEA.html
FinancialData/DRX/2024/RawHTML/DRX.html
File loaded: FinancialData/DRX/2024/RawHTML/DRX.html
FinancialData/RCE/2024/RawHTML/RCE.html
File loaded: FinancialData/RCE/2024/RawHTML/RCE.html
FinancialData/OMH/2024/RawHTML/OMH.html
File loaded: FinancialData/OMH/2024/RawHTML/OMH.html
FinancialData/MAN/2024/RawHTML/MAN.html
File loaded: FinancialData/MAN/2024/RawHTML/MAN.html
FinancialData/OBL/2024/RawHTML/OBL.html
File loaded: FinancialData/OBL/2024/RawHTML/OBL.html
FinancialData/TIG/2024/RawHTML/TIG.html
File loaded: FinancialData/TIG/2024/RawHTML/TIG.html
FinancialData/PCH/2024/RawHTML/PCH.html
File loaded: FinancialData/PCH/2024/RawHTML/PCH.html
FinancialData/XF1/2024/RawHTML/XF1.html
File loaded: FinancialData/XF1/2024/RawHTML/XF1.html
FinancialData/MME/2024/RawHTML/MME.html
File loaded: FinancialData/MME/2024/RawHTML/MME.html
FinancialData/AAP/2024/RawHTML/AAP.html
File loaded: FinancialData/AAP/2024/RawHTML/AAP.html
FinancialData/AGI/2024/RawHTML/AGI.html
File loaded: FinancialData/AGI/2024/RawHTML/AGI.html
FinancialData/CBR/2024/RawHTML/CBR.html
File loaded: FinancialData/CBR/2024/RawHTML/CBR.html
FinancialData/PLL/2024/RawHTML/PLL.html
File loaded: FinancialData/PLL/2024/RawHTML/PLL.html
FinancialData/UUV/2024/RawHTML/UUV.html
File loaded: FinancialData/UUV/2024/RawHTML/UUV.html
FinancialData/MDX/2024/RawHTML/MDX.html
File loaded: FinancialData/MDX/2024/RawHTML/MDX.html
FinancialData/ABX/2024/RawHTML/ABX.html
File loaded: FinancialData/ABX/2024/RawHTML/ABX.html
FinancialData/ADA/2024/RawHTML/ADA.html
File loaded: FinancialData/ADA/2024/RawHTML/ADA.html
FinancialData/IHOO/2024/RawHTML/IHOO.html
File loaded: FinancialData/IHOO/2024/RawHTML/IHOO.html
FinancialData/CAZ/2024/RawHTML/CAZ.html
File loaded: FinancialData/CAZ/2024/RawHTML/CAZ.html
FinancialData/CGC/2024/RawHTML/CGC.html
File loaded: FinancialData/CGC/2024/RawHTML/CGC.html
FinancialData/POD/2024/RawHTML/POD.html
File loaded: FinancialData/POD/2024/RawHTML/POD.html
FinancialData/MAI/2024/RawHTML/MAI.html
File loaded: FinancialData/MAI/2024/RawHTML/MAI.html
FinancialData/JRL/2024/RawHTML/JRL.html
File loaded: FinancialData/JRL/2024/RawHTML/JRL.html
FinancialData/GNC/2024/RawHTML/GNC.html
File loaded: FinancialData/GNC/2024/RawHTML/GNC.html
FinancialData/RCB/2024/RawHTML/RCB.html
File loaded: FinancialData/RCB/2024/RawHTML/RCB.html
FinancialData/INP/2024/RawHTML/INP.html
File loaded: FinancialData/INP/2024/RawHTML/INP.html
FinancialData/FWD/2024/RawHTML/FWD.html
File loaded: FinancialData/FWD/2024/RawHTML/FWD.html
FinancialData/INIF/2024/RawHTML/INIF.html
File loaded: FinancialData/INIF/2024/RawHTML/INIF.html
FinancialData/TEK/2024/RawHTML/TEK.html
File loaded: FinancialData/TEK/2024/RawHTML/TEK.html
FinancialData/ANS/2024/RawHTML/ANS.html
File loaded: FinancialData/ANS/2024/RawHTML/ANS.html
FinancialData/ENN/2024/RawHTML/ENN.html
File loaded: FinancialData/ENN/2024/RawHTML/ENN.html
FinancialData/RFT/2024/RawHTML/RFT.html
File loaded: FinancialData/RFT/2024/RawHTML/RFT.html
FinancialData/GML/2024/RawHTML/GML.html
File loaded: FinancialData/GML/2024/RawHTML/GML.html
FinancialData/PIO/2024/RawHTML/PIO.html
File loaded: FinancialData/PIO/2024/RawHTML/PIO.html
FinancialData/RLT/2024/RawHTML/RLT.html
File loaded: FinancialData/RLT/2024/RawHTML/RLT.html
FinancialData/IAF/2024/RawHTML/IAF.html
File loaded: FinancialData/IAF/2024/RawHTML/IAF.html
FinancialData/AMN/2024/RawHTML/AMN.html
File loaded: FinancialData/AMN/2024/RawHTML/AMN.html
FinancialData/CNL/2024/RawHTML/CNL.html
File loaded: FinancialData/CNL/2024/RawHTML/CNL.html
FinancialData/RCP/2024/RawHTML/RCP.html
File loaded: FinancialData/RCP/2024/RawHTML/RCP.html
FinancialData/CD2/2024/RawHTML/CD2.html
File loaded: FinancialData/CD2/2024/RawHTML/CD2.html
FinancialData/EAX/2024/RawHTML/EAX.html
File loaded: FinancialData/EAX/2024/RawHTML/EAX.html
FinancialData/GBZ/2024/RawHTML/GBZ.html
File loaded: FinancialData/GBZ/2024/RawHTML/GBZ.html
FinancialData/EHE/2024/RawHTML/EHE.html
File loaded: FinancialData/EHE/2024/RawHTML/EHE.html
FinancialData/RFF/2024/RawHTML/RFF.html
File loaded: FinancialData/RFF/2024/RawHTML/RFF.html
FinancialData/CMC/2024/RawHTML/CMC.html
File loaded: FinancialData/CMC/2024/RawHTML/CMC.html
FinancialData/KNO/2024/RawHTML/KNO.html
File loaded: FinancialData/KNO/2024/RawHTML/KNO.html
FinancialData/AHX/2024/RawHTML/AHX.html
File loaded: FinancialData/AHX/2024/RawHTML/AHX.html
FinancialData/ANA/2024/RawHTML/ANA.html
File loaded: FinancialData/ANA/2024/RawHTML/ANA.html
FinancialData/IMM/2024/RawHTML/IMM.html
File loaded: FinancialData/IMM/2024/RawHTML/IMM.html
FinancialData/EMT/2024/RawHTML/EMT.html
File loaded: FinancialData/EMT/2024/RawHTML/EMT.html
FinancialData/RCW/2024/RawHTML/RCW.html
File loaded: FinancialData/RCW/2024/RawHTML/RCW.html
FinancialData/4CE/2024/RawHTML/4CE.html
File loaded: FinancialData/4CE/2024/RawHTML/4CE.html
FinancialData/AKP/2024/RawHTML/AKP.html
File loaded: FinancialData/AKP/2024/RawHTML/AKP.html
FinancialData/AMI/2024/RawHTML/AMI.html
File loaded: FinancialData/AMI/2024/RawHTML/AMI.html
FinancialData/DTS/2024/RawHTML/DTS.html
File loaded: FinancialData/DTS/2024/RawHTML/DTS.html
FinancialData/AD8/2024/RawHTML/AD8.html
File loaded: FinancialData/AD8/2024/RawHTML/AD8.html
FinancialData/KBC/2024/RawHTML/KBC.html
File loaded: FinancialData/KBC/2024/RawHTML/KBC.html
FinancialData/ADT/2024/RawHTML/ADT.html
File loaded: FinancialData/ADT/2024/RawHTML/ADT.html
FinancialData/IAA/2024/RawHTML/IAA.html
File loaded: FinancialData/IAA/2024/RawHTML/IAA.html
FinancialData/SSM/2024/RawHTML/SSM.html
File loaded: FinancialData/SSM/2024/RawHTML/SSM.html
FinancialData/MGE/2024/RawHTML/MGE.html
File loaded: FinancialData/MGE/2024/RawHTML/MGE.html
FinancialData/WSP/2024/RawHTML/WSP.html
File loaded: FinancialData/WSP/2024/RawHTML/WSP.html
FinancialData/CMD/2024/RawHTML/CMD.html
File loaded: FinancialData/CMD/2024/RawHTML/CMD.html
FinancialData/KNH/2024/RawHTML/KNH.html
File loaded: FinancialData/KNH/2024/RawHTML/KNH.html
FinancialData/PEC/2024/RawHTML/PEC.html
File loaded: FinancialData/PEC/2024/RawHTML/PEC.html
FinancialData/BTC/2024/RawHTML/BTC.html
File loaded: FinancialData/BTC/2024/RawHTML/BTC.html
FinancialData/EGF/2024/RawHTML/EGF.html
File loaded: FinancialData/EGF/2024/RawHTML/EGF.html
FinancialData/RIE/2024/RawHTML/RIE.html
File loaded: FinancialData/RIE/2024/RawHTML/RIE.html
FinancialData/CDY/2024/RawHTML/CDY.html
File loaded: FinancialData/CDY/2024/RawHTML/CDY.html
FinancialData/CMM/2024/RawHTML/CMM.html
File loaded: FinancialData/CMM/2024/RawHTML/CMM.html
FinancialData/TCN/2024/RawHTML/TCN.html
File loaded: FinancialData/TCN/2024/RawHTML/TCN.html
FinancialData/FRN/2024/RawHTML/FRN.html
File loaded: FinancialData/FRN/2024/RawHTML/FRN.html
FinancialData/ANO/2024/RawHTML/ANO.html
File loaded: FinancialData/ANO/2024/RawHTML/ANO.html
FinancialData/IMC/2024/RawHTML/IMC.html
File loaded: FinancialData/IMC/2024/RawHTML/IMC.html
FinancialData/ENR/2024/RawHTML/ENR.html
File loaded: FinancialData/ENR/2024/RawHTML/ENR.html
FinancialData/MKG/2024/RawHTML/MKG.html
File loaded: FinancialData/MKG/2024/RawHTML/MKG.html
FinancialData/EGO/2024/RawHTML/EGO.html
File loaded: FinancialData/EGO/2024/RawHTML/EGO.html
FinancialData/MDC/2024/RawHTML/MDC.html
File loaded: FinancialData/MDC/2024/RawHTML/MDC.html
FinancialData/OGA/2024/RawHTML/OGA.html
File loaded: FinancialData/OGA/2024/RawHTML/OGA.html
FinancialData/CDP/2024/RawHTML/CDP.html
File loaded: FinancialData/CDP/2024/RawHTML/CDP.html
FinancialData/SPK/2024/RawHTML/SPK.html
File loaded: FinancialData/SPK/2024/RawHTML/SPK.html
FinancialData/AGR/2024/RawHTML/AGR.html
File loaded: FinancialData/AGR/2024/RawHTML/AGR.html
FinancialData/IBG/2024/RawHTML/IBG.html
File loaded: FinancialData/IBG/2024/RawHTML/IBG.html
FinancialData/EM1/2024/RawHTML/EM1.html
File loaded: FinancialData/EM1/2024/RawHTML/EM1.html
FinancialData/OKJ/2024/RawHTML/OKJ.html
File loaded: FinancialData/OKJ/2024/RawHTML/OKJ.html
FinancialData/REG/2024/RawHTML/REG.html
File loaded: FinancialData/REG/2024/RawHTML/REG.html
FinancialData/MHH/2024/RawHTML/MHH.html
File loaded: FinancialData/MHH/2024/RawHTML/MHH.html
FinancialData/HWK/2024/RawHTML/HWK.html
File loaded: FinancialData/HWK/2024/RawHTML/HWK.html
FinancialData/DTZ/2024/RawHTML/DTZ.html
File loaded: FinancialData/DTZ/2024/RawHTML/DTZ.html
FinancialData/CNB/2024/RawHTML/CNB.html
File loaded: FinancialData/CNB/2024/RawHTML/CNB.html
FinancialData/CAF/2024/RawHTML/CAF.html
File loaded: FinancialData/CAF/2024/RawHTML/CAF.html
FinancialData/AD1/2024/RawHTML/AD1.html
File loaded: FinancialData/AD1/2024/RawHTML/AD1.html
FinancialData/TOE/2024/RawHTML/TOE.html
File loaded: FinancialData/TOE/2024/RawHTML/TOE.html
FinancialData/PIA/2024/RawHTML/PIA.html
File loaded: FinancialData/PIA/2024/RawHTML/PIA.html
FinancialData/MGL/2024/RawHTML/MGL.html
File loaded: FinancialData/MGL/2024/RawHTML/MGL.html
FinancialData/MAU/2024/RawHTML/MAU.html
File loaded: FinancialData/MAU/2024/RawHTML/MAU.html
FinancialData/SPL/2024/RawHTML/SPL.html
File loaded: FinancialData/SPL/2024/RawHTML/SPL.html
FinancialData/VIV/2024/RawHTML/VIV.html
File loaded: FinancialData/VIV/2024/RawHTML/VIV.html
FinancialData/TLM/2024/RawHTML/TLM.html
File loaded: FinancialData/TLM/2024/RawHTML/TLM.html
FinancialData/YPB/2024/RawHTML/YPB.html
File loaded: FinancialData/YPB/2024/RawHTML/YPB.html
FinancialData/EGH/2024/RawHTML/EGH.html
File loaded: FinancialData/EGH/2024/RawHTML/EGH.html
FinancialData/HRZ/2024/RawHTML/HRZ.html
File loaded: FinancialData/HRZ/2024/RawHTML/HRZ.html
FinancialData/EHL/2024/RawHTML/EHL.html
File loaded: FinancialData/EHL/2024/RawHTML/EHL.html
FinancialData/AHQ/2024/RawHTML/AHQ.html
File loaded: FinancialData/AHQ/2024/RawHTML/AHQ.html
FinancialData/IMD/2024/RawHTML/IMD.html
File loaded: FinancialData/IMD/2024/RawHTML/IMD.html
FinancialData/FRI/2024/RawHTML/FRI.html
File loaded: FinancialData/FRI/2024/RawHTML/FRI.html
FinancialData/PO3/2024/RawHTML/PO3.html
File loaded: FinancialData/PO3/2024/RawHTML/PO3.html
FinancialData/GGE/2024/RawHTML/GGE.html
File loaded: FinancialData/GGE/2024/RawHTML/GGE.html
FinancialData/CAA/2024/RawHTML/CAA.html
File loaded: FinancialData/CAA/2024/RawHTML/CAA.html
FinancialData/ABC/2024/RawHTML/ABC.html
File loaded: FinancialData/ABC/2024/RawHTML/ABC.html
FinancialData/AMG/2024/RawHTML/AMG.html
File loaded: FinancialData/AMG/2024/RawHTML/AMG.html
FinancialData/IHR/2024/RawHTML/IHR.html
File loaded: FinancialData/IHR/2024/RawHTML/IHR.html
FinancialData/QUAL/2024/RawHTML/QUAL.html
File loaded: FinancialData/QUAL/2024/RawHTML/QUAL.html
FinancialData/GNX/2024/RawHTML/GNX.html
File loaded: FinancialData/GNX/2024/RawHTML/GNX.html
FinancialData/REZ/2024/RawHTML/REZ.html
File loaded: FinancialData/REZ/2024/RawHTML/REZ.html
FinancialData/BWX/2024/RawHTML/BWX.html
File loaded: FinancialData/BWX/2024/RawHTML/BWX.html
FinancialData/NTI/2024/RawHTML/NTI.html
File loaded: FinancialData/NTI/2024/RawHTML/NTI.html
FinancialData/TIA/2024/RawHTML/TIA.html
File loaded: FinancialData/TIA/2024/RawHTML/TIA.html
FinancialData/CGB/2024/RawHTML/CGB.html
File loaded: FinancialData/CGB/2024/RawHTML/CGB.html
FinancialData/IGL/2024/RawHTML/IGL.html
File loaded: FinancialData/IGL/2024/RawHTML/IGL.html
FinancialData/RLG/2024/RawHTML/RLG.html
File loaded: FinancialData/RLG/2024/RawHTML/RLG.html
FinancialData/MAH/2024/RawHTML/MAH.html
File loaded: FinancialData/MAH/2024/RawHTML/MAH.html
FinancialData/ED1/2024/RawHTML/ED1.html
File loaded: FinancialData/ED1/2024/RawHTML/ED1.html
FinancialData/OBJ/2024/RawHTML/OBJ.html
File loaded: FinancialData/OBJ/2024/RawHTML/OBJ.html
FinancialData/AHK/2024/RawHTML/AHK.html
File loaded: FinancialData/AHK/2024/RawHTML/AHK.html
FinancialData/ANR/2024/RawHTML/ANR.html
File loaded: FinancialData/ANR/2024/RawHTML/ANR.html
FinancialData/CMP/2024/RawHTML/CMP.html
File loaded: FinancialData/CMP/2024/RawHTML/CMP.html
FinancialData/8CO/2024/RawHTML/8CO.html
File loaded: FinancialData/8CO/2024/RawHTML/8CO.html
FinancialData/NWF/2024/RawHTML/NWF.html
File loaded: FinancialData/NWF/2024/RawHTML/NWF.html
FinancialData/S32/2024/RawHTML/S32.html
File loaded: FinancialData/S32/2024/RawHTML/S32.html
FinancialData/BRN/2024/RawHTML/BRN.html
File loaded: FinancialData/BRN/2024/RawHTML/BRN.html
FinancialData/EGR/2024/RawHTML/EGR.html
File loaded: FinancialData/EGR/2024/RawHTML/EGR.html
FinancialData/ZLD/2024/RawHTML/ZLD.html
File loaded: FinancialData/ZLD/2024/RawHTML/ZLD.html
FinancialData/CDM/2024/RawHTML/CDM.html
File loaded: FinancialData/CDM/2024/RawHTML/CDM.html
FinancialData/GGX/2024/RawHTML/GGX.html
File loaded: FinancialData/GGX/2024/RawHTML/GGX.html
FinancialData/OBM/2024/RawHTML/OBM.html
File loaded: FinancialData/OBM/2024/RawHTML/OBM.html
FinancialData/MGV/2024/RawHTML/MGV.html
File loaded: FinancialData/MGV/2024/RawHTML/MGV.html
FinancialData/FUEL/2024/RawHTML/FUEL.html
File loaded: FinancialData/FUEL/2024/RawHTML/FUEL.html
FinancialData/QVE/2024/RawHTML/QVE.html
File loaded: FinancialData/QVE/2024/RawHTML/QVE.html
FinancialData/INV/2024/RawHTML/INV.html
File loaded: FinancialData/INV/2024/RawHTML/INV.html
FinancialData/KMT/2024/RawHTML/KMT.html
File loaded: FinancialData/KMT/2024/RawHTML/KMT.html
FinancialData/GNE/2024/RawHTML/GNE.html
File loaded: FinancialData/GNE/2024/RawHTML/GNE.html
FinancialData/RE1/2024/RawHTML/RE1.html
File loaded: FinancialData/RE1/2024/RawHTML/RE1.html
FinancialData/QSS/2024/RawHTML/QSS.html
File loaded: FinancialData/QSS/2024/RawHTML/QSS.html
FinancialData/NXE/2024/RawHTML/NXE.html
File loaded: FinancialData/NXE/2024/RawHTML/NXE.html
FinancialData/SVH/2024/RawHTML/SVH.html
File loaded: FinancialData/SVH/2024/RawHTML/SVH.html
FinancialData/SPQ/2024/RawHTML/SPQ.html
File loaded: FinancialData/SPQ/2024/RawHTML/SPQ.html
FinancialData/VOR/2024/RawHTML/VOR.html
File loaded: FinancialData/VOR/2024/RawHTML/VOR.html
FinancialData/AGH/2024/RawHTML/AGH.html
File loaded: FinancialData/AGH/2024/RawHTML/AGH.html
FinancialData/WPL/2024/RawHTML/WPL.html
File loaded: FinancialData/WPL/2024/RawHTML/WPL.html
FinancialData/ROO/2024/RawHTML/ROO.html
File loaded: FinancialData/ROO/2024/RawHTML/ROO.html
FinancialData/RFR/2024/RawHTML/RFR.html
File loaded: FinancialData/RFR/2024/RawHTML/RFR.html
FinancialData/PCI/2024/RawHTML/PCI.html
File loaded: FinancialData/PCI/2024/RawHTML/PCI.html
FinancialData/BRI/2024/RawHTML/BRI.html
File loaded: FinancialData/BRI/2024/RawHTML/BRI.html
FinancialData/CMW/2024/RawHTML/CMW.html
File loaded: FinancialData/CMW/2024/RawHTML/CMW.html
FinancialData/IHCB/2024/RawHTML/IHCB.html
File loaded: FinancialData/IHCB/2024/RawHTML/IHCB.html
FinancialData/AHL/2024/RawHTML/AHL.html
File loaded: FinancialData/AHL/2024/RawHTML/AHL.html
FinancialData/SPX/2024/RawHTML/SPX.html
File loaded: FinancialData/SPX/2024/RawHTML/SPX.html
FinancialData/SVA/2024/RawHTML/SVA.html
File loaded: FinancialData/SVA/2024/RawHTML/SVA.html
FinancialData/DXB/2024/RawHTML/DXB.html
File loaded: FinancialData/DXB/2024/RawHTML/DXB.html
FinancialData/GMC/2024/RawHTML/GMC.html
File loaded: FinancialData/GMC/2024/RawHTML/GMC.html
FinancialData/HRN/2024/RawHTML/HRN.html
File loaded: FinancialData/HRN/2024/RawHTML/HRN.html
FinancialData/ENA/2024/RawHTML/ENA.html
File loaded: FinancialData/ENA/2024/RawHTML/ENA.html
FinancialData/EHX/2024/RawHTML/EHX.html
File loaded: FinancialData/EHX/2024/RawHTML/EHX.html
FinancialData/MMM/2024/RawHTML/MMM.html
File loaded: FinancialData/MMM/2024/RawHTML/MMM.html
FinancialData/LRS/2024/RawHTML/LRS.html
File loaded: FinancialData/LRS/2024/RawHTML/LRS.html
FinancialData/NWH/2024/RawHTML/NWH.html
File loaded: FinancialData/NWH/2024/RawHTML/NWH.html
FinancialData/CAU/2024/RawHTML/CAU.html
File loaded: FinancialData/CAU/2024/RawHTML/CAU.html
FinancialData/CGL/2024/RawHTML/CGL.html
File loaded: FinancialData/CGL/2024/RawHTML/CGL.html
FinancialData/ABW/2024/RawHTML/ABW.html

In [ ]:

def extract_financial_statements(html_content):
    dfs = pd.read_html(StringIO(html_content))
    dfs = [df for df in dfs[20:-2] if df.shape[0] >= 10]
    df_names = ['profit_loss',
                'balance_sheet',
                'cash_flow',
                'per_share_statiscs',
                'rev_exp', #cho nay dang ngu 
                'sundry_analysis',
                'growth_rates',
                'ratio_analysis',
                'asset_bate']
    res = {
        k:v.rename(columns={v.columns[0]: 'metrics'})
        for k,v in zip(df_names, dfs)
        if k != 'rev_exp'
    }

    return res

In [18]:
comp_info = {k:extract_financial_statements(v) for k,v in comp_data.items()}

/var/folders/3y/dd2_h5492gj2f1b01t_fksph0000gn/T/ipykernel_85148/2120142303.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  statements = pd.read_html(html_content)

In [19]:
import requests
import json

url = "https://www.marketindex.com.au/api/v1/companies"

payload = {}
headers = {
  'sec-ch-ua': '"Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"',
  'X-NewRelic-ID': 'VwAHUlZaCRAFXFNTAQAHUlI=',
  'correlation-id': '01HVGRE75SSGVH5X3KWXHCNNM1',
  'X-XSRF-TOKEN': 'eyJpdiI6InptQ3RIQXpDTkdScWltdXRKR09MdGc9PSIsInZhbHVlIjoiMHEydzRPWHRHTkxXSXFrNjQwVmliOFhXNTZrcUUzcFFIWWxsc3NqTjJrb3JieXBJYlVzMzFkMUtzU3VKRnRlNFZmZ0ttWUFJeFByTXpieWVDQzVIaXJyVWQrd0Nnd3JuSnRmd1BNcWJEWTNVTXdCb0VFS0pFTUxpZnVSNnlZKzQiLCJtYWMiOiI0YWVhMzJmNTA1OWJlODE1YTdiMzVkMGUxMDVlZmRlZTJjYzhmZmViNDU5MWE2NDE0Yjg3M2ExMzJhYzUwOTJmIiwidGFnIjoiIn0=',
  'tracestate': '3603091@nr=0-1-3603091-594456136-69285a68966786da----1713181507459',
  'X-CSRF-TOKEN': 'FMZhXZiNbaoAc7grdxHcCpr2tI0s38MXNKjoIZJO',
  'traceparent': '00-91ab728ebadbfd16aec096ca8bb11e42-69285a68966786da-01',
  'sec-ch-ua-mobile': '?0',
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
  'newrelic': 'eyJ2IjpbMCwxXSwiZCI6eyJ0eSI6IkJyb3dzZXIiLCJhYyI6IjM2MDMwOTEiLCJhcCI6IjU5NDQ1NjEzNiIsImlkIjoiNjkyODVhNjg5NjY3ODZkYSIsInRyIjoiOTFhYjcyOGViYWRiZmQxNmFlYzA5NmNhOGJiMTFlNDIiLCJ0aSI6MTcxMzE4MTUwNzQ1OX19',
  'Accept': 'application/json, text/plain, */*',
  'Referer': 'https://www.marketindex.com.au/asx-listed-companies',
  'sec-ch-ua-platform': '"macOS"'
}

response = requests.request("GET", url, headers=headers, data=payload)
active_symbols = [x['code'] for x in response.json()]

crawl_symbol = set(pd.read_csv('20200501-asx-listed-companies.csv',skiprows=1)['Code'].to_list())
active_symbols = set(active_symbols)
res = active_symbols.intersection(crawl_symbol)

In [20]:
SYMBOLS = pd.read_csv('symbols.csv')['code']

,($millions),09/14,09/15,09/16,09/17,09/18,09/19,09/20,09/21,09/22,09/23
0,Operating Cash Flow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Interest Received,29327.0,30667.0,29992.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Interest Paid,-14886.0,-15458.0,-15038.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Dividends Received,127.0,231.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Tax Paid,-3207.0,-3082.0,-2840.0,-2864.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Other Operating Cash Flow,-5718.0,9118.0,-1393.0,26836.0,10566.0,-4550.0,52284.0,43822.0,20176.0,6488.0
6,Net Operating Cash Flow,5643.0,21476.0,10841.0,23972.0,10566.0,-4550.0,52284.0,43822.0,20176.0,6488.0
7,Investing Cash Flow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Payment for Purchase of PPE,-370.0,-321.0,-337.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Proceeds from Sale of PPE,0.0,0.0,6699.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Investments Purchased,-12652.0,-24236.0,-44182.0,-27220.0,-23806.0,-23847.0,-40029.0,-52639.0,-34292.0,-52030.0
11,Proceeds from Sale of Investments,11136.0,15705.0,23745.0,19751.0,20592.0,21228.0,28642.0,63445.0,32797.0,41401.0
12,Payments for Purchase of Subsidiaries,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-65.0,-10.0
13,Proceeds from Sale of Subsidiaries,251.0,4.0,0.0,0.0,0.0,2121.0,1309.0,13.0,394.0,558.0
14,Loans Granted,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Loans Repaid,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,Other Investing Cash Flow,-292.0,-928.0,-335.0,-5361.0,3380.0,292.0,-1387.0,-561.0,-651.0,-605.0
17,Net Investing Cash Flow,-1927.0,-9776.0,-14410.0,-12830.0,166.0,-206.0,-11465.0,10258.0,-1817.0,-10686.0
18,Financing Cash Flow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Proceeds from Issues,4.0,3207.0,0.0,0.0,0.0,0.0,0.0,0.0,3989.0,0.0
20,Proceeds from Borrowings,20414.0,19320.0,35381.0,25128.0,25075.0,25900.0,12260.0,21934.0,24648.0,33077.0
21,Repayment of Borrowings,-13296.0,-15966.0,-28859.0,-27409.0,-15898.0,-22958.0,-21711.0,-28039.0,-26235.0,-24291.0
22,Dividends Paid,-3827.0,-3763.0,-4564.0,-4210.0,-4563.0,-4471.0,-2861.0,-2834.0,-3784.0,-4380.0
23,Other Financing Cash Flow,-500.0,-755.0,0.0,-176.0,-1994.0,-1232.0,-122.0,-733.0,-963.0,-21.0
24,Net Financing Cash Flow,2795.0,2043.0,1958.0,-6667.0,2620.0,-2761.0,-12434.0,-9672.0,-2345.0,4385.0
25,Net Increase in Cash,6511.0,13743.0,-1611.0,4475.0,13352.0,-7517.0,28385.0,44408.0,16014.0,187.0
26,Cash at Beginning of Period,41111.0,48229.0,69278.0,66220.0,68048.0,84964.0,81621.0,107923.0,151260.0,168132.0
27,Exchange Rate Adj,607.0,7306.0,-1447.0,-2647.0,3564.0,4174.0,-2083.0,-1071.0,858.0,-165.0
28,Cash at End of Period,48229.0,69278.0,66220.0,68048.0,84964.0,81621.0,107923.0,151260.0,168132.0,168154.0

In [21]:
balance_sheet

,($millions),09/14,09/15,09/16,09/17,09/18,09/19,09/20,09/21,09/22,09/23
0,Earning Assets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Short Term Money,22708.0,41850.0,27475.0,46569.0,56334.0,56344.0,72320.0,133689.0,152136.0,136443.0
2,Investment Securities,128621.0,144980.0,171429.0,174680.0,142861.0,156031.0,182071.0,147357.0,139567.0,168493.0
3,Due From Banks,0.0,0.0,0.0,0.0,2319.0,3739.0,7541.0,7530.0,4762.0,9349.0
4,Loans,521752.0,580769.0,597803.0,579835.0,603938.0,615258.0,617093.0,629719.0,672407.0,707044.0
5,Total Earning Assets,673081.0,767599.0,796707.0,801084.0,805452.0,831372.0,879025.0,918295.0,968872.0,1021329.0
6,Non-Earning Assets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Customer Acceptances,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Fixed Assets,2181.0,2221.0,2205.0,1965.0,1833.0,1924.0,3013.0,2734.0,2431.0,2053.0
9,Other,96830.0,120080.0,115957.0,94277.0,135339.0,147841.0,160248.0,57828.0,114426.0,82238.0
10,Total Non-Earning Assets,99011.0,122301.0,118162.0,96242.0,137172.0,149765.0,163261.0,60562.0,116857.0,84291.0
11,Total Assets,772092.0,889900.0,914869.0,897326.0,942624.0,981137.0,1042286.0,978857.0,1085729.0,1105620.0
12,Liabilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Due to Banks,0.0,0.0,10625.0,9914.0,11810.0,10867.0,22241.0,17427.0,13766.0,19267.0
14,Bank Acceptances,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Deposits,493527.0,546228.0,505418.0,581190.0,600278.0,625865.0,673191.0,717372.0,758059.0,781600.0
16,Provisions,1669.0,1590.0,1624.0,1656.0,1937.0,3139.0,3604.0,3305.0,3333.0,2673.0
17,Bonds,30159.0,41575.0,104741.0,122394.0,139051.0,141503.0,128810.0,126738.0,132956.0,149125.0
18,Other,197453.0,243154.0,234534.0,123097.0,130165.0,138969.0,153143.0,50339.0,111214.0,82909.0
19,Total Liabilities,722808.0,832547.0,856942.0,838251.0,883241.0,920343.0,980989.0,915181.0,1019328.0,1035574.0
20,Shareholders Equity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Share Capital,24031.0,28367.0,28765.0,29088.0,27205.0,26490.0,26531.0,25984.0,28797.0,29082.0
22,Reserves,-239.0,1571.0,1078.0,37.0,323.0,1629.0,1501.0,1228.0,-2606.0,-1735.0
23,Retained Earnings,24544.0,27309.0,27975.0,29834.0,31715.0,32664.0,33255.0,36453.0,39716.0,42177.0
24,Other Equity,871.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Convertible Equity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,SE Held Sale,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Outside Equity,77.0,106.0,109.0,116.0,140.0,11.0,10.0,11.0,494.0,522.0
28,Total Equity,49284.0,57353.0,57927.0,59075.0,59383.0,60794.0,61297.0,63676.0,66401.0,70046.0

In [17]:
balance_sheet.to_csv('CleanedData/balance_sheet_ANZ.csv')

In [ ]:
def get_dict_depth(d, depth=0):
    """
    Recursively finds the depth of nesting in a dictionary.

    Args:
    d (dict): The dictionary to check.
    depth (int): The current depth level, defaults to 0.

    Returns:
    int: Maximum depth of nesting found in the dictionary.
    """
    if isinstance(d, dict):
        return max([get_dict_depth(v, depth + 1) for v in d.values()], default=depth)  # Use default to handle empty dicts
    return depth


def store_csv_data(financial_data, SYMBOLS, depth):
    """
    Stores each stock's financial data as a CSV file.
    
    Parameters:
    - financial_data: Dictionary with ASX codes as keys and another dictionary as values,
                      where the inner dictionary has keys as DataFrame names and values as pandas DataFrames.
    - SYMBOLS: Not directly used in this function, may be considered for filtering or validation if needed.
    """
    output_dir = 'CleanedData'
    os.makedirs(output_dir, exist_ok=True)  # Ensure the directory exists

    # Iterate over the financial_data dictionary
    for stock_symbol, dataframes in financial_data.items():
        stock_dir = os.path.join(output_dir, stock_symbol)
        os.makedirs(stock_dir, exist_ok=True)  # Create a directory for each stock symbol if it doesn't exist
        
        if depth == 1:
            csv_path = os.path.join(stock_dir, f'hist_prices_20120501_20230601.csv')
            try:
                dataframes.to_csv(csv_path, index=False)
                print(f'Saved CSV for {stock_symbol} at {csv_path}')
            except Exception as e:
                print(f'Error saving {csv_path}: {str(e)}')
                
                
        if depth == 2:
            # Iterate over each DataFrame associated with the stock symbol
            for df_name, df in dataframes.items():
                csv_path = os.path.join(stock_dir, f'{df_name}.csv')
                try:
                    df.to_csv(csv_path, index=False)
                    print(f'Saved CSV for {stock_symbol} at {csv_path}')
                except Exception as e:
                    print(f'Error saving {stock_symbol}/{df_name}.csv: {str(e)}')

In [ ]:
#store_csv_data(comp_info, SYMBOLS, get_dict_depth(comp_info))

In [ ]:
get_prices = lambda x: (
    yf.Ticker(x)
    .history(
        period='1d', 
        start='2012-05-01', 
        end='2023-06-01'))
unavail_symbol = []

hist_prices = {
    symbol: result
    if ((result := get_prices(symbol)) is not None) and not result.empty
    else unavail_symbol.append(symbol)
    for symbol in SYMBOLS
}

In [ ]:
#store_csv_data(hist_prices, SYMBOLS=SYMBOLS, depth=get_dict_depth(hist_prices))

In [ ]:
pd.DataFrame({
    'delisted_symbols': unavail_symbol
}).to_csv('unavail_hist_price_symbol.csv')